const KEY='arrahnu_fresh_tickets_v1';
const $=id=>document.getElementById(id);
const today=()=>new Date().toISOString().slice(0,10);
const uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());
const rm=n=>`RM ${Number(n||0).toLocaleString('ms-MY',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
let tickets=JSON.parse(localStorage.getItem(KEY)||'[]');
let currentDetailId=null;
let deferredInstallPrompt=null;
let currentImageData='';
let currentImageFile=null;

const pageTitles={dashboard:'Dashboard',senarai:'Senarai Surat',detail:'Detail Surat',kiraan:'Kiraan',upload:'Upload Surat'};
function save(){localStorage.setItem(KEY,JSON.stringify(tickets));renderAll();}
function go(page){document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));$(`page-${page}`).classList.add('active');$('pageTitle').textContent=pageTitles[page]||'Ar-Rahnu';document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.nav===page));if(page==='kiraan')renderCalcOptions();window.scrollTo({top:0,behavior:'smooth'});}
document.addEventListener('click',e=>{const btn=e.target.closest('[data-nav]');if(btn)go(btn.dataset.nav);});

function monthsBetween(start,end=new Date()){const s=new Date(start);return Math.max(0,(end.getFullYear()-s.getFullYear())*12+(end.getMonth()-s.getMonth())+(end.getDate()>=s.getDate()?0:-1));}
function addMonths(date,months){const d=new Date(date);d.setMonth(d.getMonth()+Number(months||0));return d;}
function activeItems(t){return (t.items||[]).filter(i=>!i.redeemed);}
function remainingPrincipal(t){return activeItems(t).reduce((a,i)=>a+Number(i.value||0),0)||Number(t.remainingPrincipal||t.principal||0);}
function monthlyRate(t){const rate=Number(t.rate||0)/100;return t.rateMode==='year'?rate/12:rate;}
function upahForAmount(t,amount){return Number(amount||0)*monthlyRate(t)*Math.max(1,monthsBetween(t.startDate));}
function expiryDate(t){return addMonths(t.startDate,Number(t.tenure||6));}
function statusOf(t){if(t.status==='redeemed')return 'redeemed';const days=Math.ceil((expiryDate(t)-new Date())/86400000);if(days<0)return 'overdue';if(days<=14)return 'warning';return 'active';}
function statusLabel(s){return {active:'Aktif',warning:'Amaran',overdue:'Lewat',redeemed:'Selesai'}[s]||s;}

function renderStats(){const active=tickets.filter(t=>statusOf(t)!=='redeemed');const principal=active.reduce((a,t)=>a+remainingPrincipal(t),0);const warn=tickets.filter(t=>['warning','overdue'].includes(statusOf(t))).length;$('statsGrid').innerHTML=`<div class="stat-card"><b>${active.length}</b><span>Aktif</span></div><div class="stat-card"><b>${rm(principal)}</b><span>Baki</span></div><div class="stat-card"><b>${warn}</b><span>Amaran</span></div>`;}
function ticketCard(t){const st=statusOf(t);return `<article class="ticket-card" data-open="${t.id}"><div class="ticket-head"><div><h3>${t.ticketNo} — ${t.customer.name}</h3><p class="muted">${rm(remainingPrincipal(t))} • ${activeItems(t).length}/${(t.items||[]).length} item aktif</p></div><span class="badge ${st}">${statusLabel(st)}</span></div><div class="meta-grid"><div><small class="muted">Due</small><br><b>${expiryDate(t).toLocaleDateString('ms-MY')}</b></div><div><small class="muted">Harga emas</small><br><b>${rm(t.goldPrice)}/g</b></div></div></article>`;}
function renderDashboard(){renderStats();const active=tickets.filter(t=>statusOf(t)!=='redeemed').slice(0,4);$('activeTickets').innerHTML=active.length?active.map(ticketCard).join(''):'<p class="muted">Belum ada surat. Klik Upload Surat untuk mula.</p>';}
function renderList(){const q=$('searchInput').value.toLowerCase();const f=$('statusFilter').value;const rows=tickets.filter(t=>{const hay=`${t.ticketNo} ${t.customer.name} ${t.customer.ic}`.toLowerCase();const st=statusOf(t);return hay.includes(q)&&(f==='all'||st===f);});$('ticketList').innerHTML=rows.length?rows.map(ticketCard).join(''):'<p class="muted">Tiada rekod jumpa.</p>';}
document.addEventListener('click',e=>{const card=e.target.closest('[data-open]');if(card){currentDetailId=card.dataset.open;renderDetail();go('detail');}});
$('searchInput').addEventListener('input',renderList);$('statusFilter').addEventListener('change',renderList);

function renderDetail(){const t=tickets.find(x=>x.id===currentDetailId);if(!t){$('ticketDetail').innerHTML='<p class="muted">Surat tak dijumpai.</p>';return;}const st=statusOf(t);const img=t.imageData?`<section class="card"><h2>Gambar Surat</h2><img class="ticket-image" src="${t.imageData}" alt="Gambar surat ${t.ticketNo}"></section>`:'';$('ticketDetail').innerHTML=`<section class="detail-hero"><h2>${t.ticketNo}</h2><p>${t.customer.name} • ${t.customer.ic||'-'}</p><p><b>${statusLabel(st)}</b> • Baki ${rm(remainingPrincipal(t))}</p></section>${img}<section class="card"><h2>Maklumat</h2><div class="meta-grid"><div>Pinjaman Asal<br><b>${rm(t.principal)}</b></div><div>Baki<br><b>${rm(remainingPrincipal(t))}</b></div><div>Mula<br><b>${new Date(t.startDate).toLocaleDateString('ms-MY')}</b></div><div>Tamat<br><b>${expiryDate(t).toLocaleDateString('ms-MY')}</b></div></div></section><section class="card"><h2>Item Gadaian</h2>${(t.items||[]).map(i=>`<div class="item-pill"><span>${i.redeemed?'✅':'💎'} ${i.description} (${i.weight||0}g)</span><b>${rm(i.value)}</b></div>`).join('')}</section><section class="card"><h2>History</h2><div class="history">${(t.transactions||[]).map(x=>`<div class="history-item"><b>${x.type}</b><br><span class="muted">${new Date(x.createdAt).toLocaleString('ms-MY')} — ${rm(x.totalPaid||x.amount)}</span></div>`).join('')||'<p class="muted">Belum ada transaksi.</p>'}</div><button class="primary-btn" onclick="currentDetailId='${t.id}';go('kiraan')">Buat Kiraan</button></section>`;}

function renderCalcOptions(){const active=tickets.filter(t=>statusOf(t)!=='redeemed');$('calcTicket').innerHTML=active.map(t=>`<option value="${t.id}">${t.ticketNo} — ${t.customer.name}</option>`).join('')||'<option value="">Tiada surat aktif</option>';renderCalcItems();$('calcResult').innerHTML='Pilih surat dan jenis kiraan dahulu.';}
$('calcTicket').addEventListener('change',renderCalcItems);$('calcType').addEventListener('change',()=>{const type=$('calcType').value;$('partialBox').hidden=type!=='partial';$('overlapBox').hidden=type!=='overlap';});
function renderCalcItems(){const t=tickets.find(x=>x.id===$('calcTicket').value)||tickets.find(x=>x.id===currentDetailId);if(t&&currentDetailId)$('calcTicket').value=t.id;$('calcItems').innerHTML=t?activeItems(t).map(i=>`<label class="check-item"><input type="checkbox" value="${i.id}"> ${i.description} — ${rm(i.value)}</label>`).join(''):'<p class="muted">Tiada item.</p>';}
$('runCalcBtn').addEventListener('click',()=>{const t=tickets.find(x=>x.id===$('calcTicket').value);if(!t)return;const type=$('calcType').value;let html='';if(type==='partial'){const ids=[...$('calcItems').querySelectorAll('input:checked')].map(i=>i.value);const items=activeItems(t).filter(i=>ids.includes(i.id));const principal=items.reduce((a,i)=>a+Number(i.value),0);const upah=upahForAmount(t,principal);html=`<b>Tebus Sebahagian</b><div class="result-line">Prinsipal item: ${rm(principal)}</div><div class="result-line">Upah anggaran: ${rm(upah)}</div><div class="result-line"><b>Total bayar: ${rm(principal+upah)}</b></div>`;}if(type==='full'){const principal=remainingPrincipal(t);const upah=upahForAmount(t,principal);html=`<b>Tebus Penuh</b><div class="result-line">Baki prinsipal: ${rm(principal)}</div><div class="result-line">Upah tertunggak: ${rm(upah)}</div><div class="result-line"><b>Total bayar: ${rm(principal+upah)}</b></div>`;}if(type==='overlap'){const principal=remainingPrincipal(t);const upah=upahForAmount(t,principal);const newLoan=Number($('newLoanAmount').value||0);html=`<b>Overlap / Renew</b><div class="result-line">Baki prinsipal: ${rm(principal)}</div><div class="result-line">Upah perlu bayar: ${rm(upah)}</div><div class="result-line">Pinjaman baru: ${rm(newLoan)}</div><div class="result-line"><b>Anggaran cash-out: ${rm(Math.max(0,newLoan-principal-upah))}</b></div>`;}$('calcResult').innerHTML=html;});

let itemDraft=[];function blankItem(){return{id:uid(),description:'',weight:'',value:''};}function renderItemEditor(){$('itemEditor').innerHTML=itemDraft.map((i,idx)=>`<div class="item-row"><input placeholder="Item #${idx+1}" value="${i.description}" data-item="${i.id}" data-field="description"><input type="number" placeholder="gram" value="${i.weight}" data-item="${i.id}" data-field="weight"><input type="number" placeholder="nilai RM" value="${i.value}" data-item="${i.id}" data-field="value"><button class="tiny-btn" data-del-item="${i.id}">×</button></div>`).join('');}
$('itemEditor').addEventListener('input',e=>{const id=e.target.dataset.item;if(!id)return;const it=itemDraft.find(x=>x.id===id);it[e.target.dataset.field]=e.target.value;});$('itemEditor').addEventListener('click',e=>{const id=e.target.dataset.delItem;if(id){itemDraft=itemDraft.filter(i=>i.id!==id);renderItemEditor();}});$('addItemBtn').addEventListener('click',()=>{itemDraft.push(blankItem());renderItemEditor();});
$('imageInput').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;currentImageFile=file;const img=$('previewImg');const reader=new FileReader();reader.onload=()=>{currentImageData=reader.result;img.src=currentImageData;img.hidden=false;};reader.readAsDataURL(file);});
function fillOcrData(data){$('fTicketNo').value=data.ticketNo||`G-${Date.now().toString().slice(-5)}`;$('fName').value=data.customer?.name||'';$('fIc').value=data.customer?.ic||'';$('fPhone').value=data.customer?.phone||'';$('fPrincipal').value=data.principal||'';$('fRate').value=data.rate||0.75;$('fRateMode').value=data.rateMode||'month';$('fStartDate').value=data.startDate||today();$('fTenure').value=data.tenure||6;itemDraft=(data.items?.length?data.items:[{description:'',weight:'',value:''}]).map(i=>({id:uid(),description:i.description||'',weight:i.weight||'',value:i.value||''}));renderItemEditor();}
$('ocrBtn').addEventListener('click',async()=>{if(!currentImageFile){alert('Upload gambar dulu.');return;}const btn=$('ocrBtn');btn.disabled=true;btn.textContent='Sedang OCR...';try{const form=new FormData();form.append('image',currentImageFile);const res=await fetch('/api/ocr/pawn-ticket',{method:'POST',body:form});const json=await res.json();if(!json.ok)throw new Error(json.error||'OCR gagal');fillOcrData(json.data||{});alert(json.mode==='openai-vision'?'Vision OCR siap. Semak field sebelum simpan.':'OCR fallback aktif. Isi/semak manual dulu.');}catch(err){console.warn(err);fillOcrData({ticketNo:`G-${Date.now().toString().slice(-5)}`,customer:{name:'Nama Pelanggan (manual)'},principal:3000,rate:.75,rateMode:'month',startDate:today(),tenure:6,items:[{description:'Rantai emas 916',weight:10,value:1800},{description:'Cincin emas 916',weight:6,value:1200}]});alert('Backend OCR belum running / error. Aku isi demo supaya flow masih boleh test.');}finally{btn.disabled=false;btn.textContent='Jalankan Vision OCR';}});
$('saveTicketBtn').addEventListener('click',()=>{const principal=Number($('fPrincipal').value||0);if(!$('fTicketNo').value||!$('fName').value||!principal)return alert('Isi no surat, nama dan pinjaman.');const cleanItems=itemDraft.filter(i=>i.description||i.value).map(i=>({...i,weight:Number(i.weight||0),value:Number(i.value||0),redeemed:false}));const t={id:uid(),ticketNo:$('fTicketNo').value.trim(),customer:{name:$('fName').value.trim(),ic:$('fIc').value.trim(),phone:$('fPhone').value.trim()},principal,remainingPrincipal:principal,goldPrice:Number($('fGoldPrice').value||0),rate:Number($('fRate').value||0),rateMode:$('fRateMode').value,startDate:$('fStartDate').value||today(),tenure:Number($('fTenure').value||6),items:cleanItems.length?cleanItems:[{...blankItem(),description:'Item emas',value:principal,redeemed:false}],transactions:[{type:'Surat dibuka',amount:principal,totalPaid:0,createdAt:new Date().toISOString()}],imageData:currentImageData,createdAt:new Date().toISOString()};tickets.unshift(t);resetForm();save();currentDetailId=t.id;renderDetail();go('detail');});
function resetForm(){['fTicketNo','fName','fIc','fPhone','fPrincipal','fGoldPrice'].forEach(id=>$(id).value='');$('fRate').value='0.75';$('fRateMode').value='month';$('fStartDate').value=today();$('fTenure').value='6';$('previewImg').hidden=true;$('previewImg').src='';$('imageInput').value='';currentImageData='';currentImageFile=null;itemDraft=[blankItem()];renderItemEditor();}
$('seedBtn').addEventListener('click',()=>{tickets=[{id:uid(),ticketNo:'G001',customer:{name:'Ali bin Abu',ic:'900101-01-1234',phone:'0123456789'},principal:5000,remainingPrincipal:5000,goldPrice:365,rate:.75,rateMode:'month',startDate:today(),tenure:6,items:[{id:uid(),description:'Rantai emas 916',weight:8,value:2500,redeemed:false},{id:uid(),description:'Gelang emas 916',weight:7,value:2500,redeemed:false}],transactions:[{type:'Surat dibuka',amount:5000,totalPaid:0,createdAt:new Date().toISOString()}],createdAt:new Date().toISOString()}];save();});
function renderAll(){renderDashboard();renderList();renderCalcOptions();if(currentDetailId)renderDetail();}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e;$('installBtn').hidden=false;});$('installBtn').addEventListener('click',async()=>{if(deferredInstallPrompt){deferredInstallPrompt.prompt();deferredInstallPrompt=null;$('installBtn').hidden=true;}});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
resetForm();renderAll();
